version: '3'

services:
  wordpress:
    build: .
    ports:
      - "31337:80"
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - "wp:/var/www/html:rw"
  mysql:
    image: "ghcr.io/kmaksymowicz/mysql:1.0"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: ghcr.io/kmaksymowicz/phpmyadmin:1.0
    ports:
      - 31338:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  wp: {}
  db: {}